### ISSUE TITLE
Pulumi files installed in wrong directory

### ISSUE THREAD

**Issue by kjsity2914** [JasonWhall/pulumi-installer-task#1]
When running the Pulumi installer task, the installed files are located inside... 

`D:\Agent\_work\_tool\pulumi\2.15.4\x64\Pulumi\bin`

Then however when running the offical Pulumi Azure Pipelines Task, it knows that the tool cache is available but tries to locate them inside a different directory...

`D:\Agent\_work\_tool\pulumi\2.15.4\x64\bin`

We then get this error...

`Found tool in cache: pulumi 2.15.4 x64
(node:19184) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Directory does not exist: D:\Agent\_work\_tool\pulumi\2.15.4\x64\bin`

**Comment by JasonWhall** [comment]
Hey @kjsity2914 thanks for opening this issue.

Just out of interest what is your use case for using this DevOps task in conjunction with the official task? The Official task already installs the deisred Pulumi version and runs the command. Just FYI The motivation for creating this DevOps task was to allow more flexibility to use scripting to orchestrate pulumi commands in one step/job and overcome some of the limitations of the installer in the official task.

Having a brief look it looks like the Official task [expects the pulumi binary to exist in a `bin` folder](https://github.com/pulumi/pulumi-az-pipelines-task/blob/db5d6c9dc6c42da75eb27fd3a91267f91b9b4f38/buildAndReleaseTask/index.ts#L50) in the DevOps agent tool cache for the pulumi tool. This isn't necessarily indicative of the way the pulumi binary gets packaged as it looks like they are stuffed in different subfolders depending on the OS.

That being said, I can certainly take a look to see if I can mimic this behaviour and store the Pulumi binary into a `bin` folder in the tool cache. Alternatively If you'd like to contribute yourself, I'm happy to accept a PR to this.

**Comment by JasonWhall** [comment]
@kjsity2914 after a bit more investigating I can see that there are multiple bugs in the official task that I am unable to cater for by changing the code in this task. The 2 issues I have found

- The official task does not actually use the Azure DevOps tool cache when it install Pulumi itself, so the code it uses to check to tool cache is invalid.
- As mentioned before, the official task expects the binary to exist in a `bin` folder. When extracting the Pulumi packages from the downloaded artifact, only the Windows version exists in a `bin` folder.

I think for the time being to keep things separate, I will rename the cached tool in this task from `pulumi` to `pulumi-cli`. This will allow the official task to handle the Pulumi installation itself without erroring and allow this task to be used independently. I will try to raise an issue on the [official task repo](https://github.com/pulumi/pulumi-az-pipelines-task) to try integrate/fix some of these issues.
